// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: chain/compute/tx.proto

package compute

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName        = "/chain.compute.Msg/UpdateParams"
	Msg_CreateComputeJob_FullMethodName    = "/chain.compute.Msg/CreateComputeJob"
	Msg_RequestJobExecution_FullMethodName = "/chain.compute.Msg/RequestJobExecution"
	Msg_CompleteJob_FullMethodName         = "/chain.compute.Msg/CompleteJob"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateComputeJob(ctx context.Context, in *MsgCreateComputeJob, opts ...grpc.CallOption) (*MsgCreateComputeJobResponse, error)
	RequestJobExecution(ctx context.Context, in *MsgRequestJobExecution, opts ...grpc.CallOption) (*MsgRequestJobExecutionResponse, error)
	CompleteJob(ctx context.Context, in *MsgCompleteJob, opts ...grpc.CallOption) (*MsgCompleteJobResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateComputeJob(ctx context.Context, in *MsgCreateComputeJob, opts ...grpc.CallOption) (*MsgCreateComputeJobResponse, error) {
	out := new(MsgCreateComputeJobResponse)
	err := c.cc.Invoke(ctx, Msg_CreateComputeJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestJobExecution(ctx context.Context, in *MsgRequestJobExecution, opts ...grpc.CallOption) (*MsgRequestJobExecutionResponse, error) {
	out := new(MsgRequestJobExecutionResponse)
	err := c.cc.Invoke(ctx, Msg_RequestJobExecution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CompleteJob(ctx context.Context, in *MsgCompleteJob, opts ...grpc.CallOption) (*MsgCompleteJobResponse, error) {
	out := new(MsgCompleteJobResponse)
	err := c.cc.Invoke(ctx, Msg_CompleteJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateComputeJob(context.Context, *MsgCreateComputeJob) (*MsgCreateComputeJobResponse, error)
	RequestJobExecution(context.Context, *MsgRequestJobExecution) (*MsgRequestJobExecutionResponse, error)
	CompleteJob(context.Context, *MsgCompleteJob) (*MsgCompleteJobResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateComputeJob(context.Context, *MsgCreateComputeJob) (*MsgCreateComputeJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComputeJob not implemented")
}
func (UnimplementedMsgServer) RequestJobExecution(context.Context, *MsgRequestJobExecution) (*MsgRequestJobExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestJobExecution not implemented")
}
func (UnimplementedMsgServer) CompleteJob(context.Context, *MsgCompleteJob) (*MsgCompleteJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteJob not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateComputeJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateComputeJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateComputeJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateComputeJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateComputeJob(ctx, req.(*MsgCreateComputeJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestJobExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestJobExecution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestJobExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RequestJobExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestJobExecution(ctx, req.(*MsgRequestJobExecution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CompleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCompleteJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CompleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CompleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CompleteJob(ctx, req.(*MsgCompleteJob))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chain.compute.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateComputeJob",
			Handler:    _Msg_CreateComputeJob_Handler,
		},
		{
			MethodName: "RequestJobExecution",
			Handler:    _Msg_RequestJobExecution_Handler,
		},
		{
			MethodName: "CompleteJob",
			Handler:    _Msg_CompleteJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chain/compute/tx.proto",
}
