version: 2
updates:
  - package-ecosystem: cargo
    directory: /trillionnium
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /tests/fuzz
    schedule:
      interval: weekly
