[package]
name = "trnm-consensus-safety-store"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
fs2 = "0.4"
getrandom = "0.2"
libc = "0.2"
rusqlite = { version = "0.32", features = ["bundled"] }
sha2 = "0.10"
trnm-consensus-core = { version = "0.1.0", path = "../trnm-consensus-core" }
trnm-consensus-types = { version = "0.1.0", path = "../trnm-consensus-types" }

[dev-dependencies]
tempfile = "3"
