#!/usr/bin/env python3
"""Derive current implementation/profile navigation from the existing authorities."""
from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[2]
DESTINATION = 'docs/architecture/CURRENT_IMPLEMENTATION.md'
INPUTS = ('config/consensus-mainline.json', 'config/pon/module-maturity-v1.json',
          'config/pon/applicability-v1.json', 'config/portability-inventory-v1.json',
          'trillionnium/Cargo.toml')


def projection(root: Path = ROOT) -> dict:
    load = lambda path: json.loads((root / path).read_text())
    truth, maturity, applicability, inventory = [load(p) for p in INPUTS[:-1]]
    cargo = tomllib.loads((root / INPUTS[-1]).read_text())
    packages = {p['package']: p for p in inventory['packages']}
    if set(cargo['workspace']['members']) != {'crates/' + name for name in packages}:
        raise ValueError('implementation summary requires the actual inventoried Cargo graph')
    modules = []
    for module in maturity['modules']:
        responsibilities = module['responsibilities']
        modules.append({'id': module['id'], 'procedures': len(responsibilities),
                        'kinds': dict(sorted(Counter(p['implementation_kind'] for p in responsibilities).items())),
                        'packages': sorted(p['package'] for p in packages.values() if p['module'] == module['id']),
                        'native_product_integrated': module['native_product_integrated'],
                        'independent_accepted': module['independent_accepted'],
                        'ordinary_product_entrypoints': sum(p['ordinary_product_entrypoint'] is not None for p in responsibilities)})
    return {'schema': 'trnm-current-implementation-projection-v1', 'authorities': list(INPUTS),
            'stage': truth['stage'], 'development_target': truth['development_target'],
            'workspace_packages': len(packages), 'modules': modules,
            'profiles': applicability['profiles'],
            'acceptance': {k: truth[k] for k in ('runtime_implemented', 'work_profile_qualified',
                'production_candidate', 'production_consensus_activation', 'public_testnet_ready', 'release_ready')},
            'tests_executed_by_reporter': False}


def markdown(data: dict) -> str:
    lines = ['# Current implementation and explicit profiles', '',
             '<!-- Generated by scripts/ci/report_current_implementation.py; do not edit by hand. -->', '',
             'This is a derived navigation view, not a second plan or an execution receipt. ',
             'Regenerate with `python3 scripts/ci/report_current_implementation.py --write`; ',
             'the repository checker rejects stale output. Historical measurements retain their original source.', '',
             f"Selected target: `{data['development_target']}`. Registered stage: `{data['stage']}`. ",
             f"Actual inventoried workspace: **{data['workspace_packages']} packages**; ",
             f"registered procedures: **{sum(m['procedures'] for m in data['modules'])}**.", '',
             '## Implementation inventory', '',
             'A native reusable package can support a module without completing its normal product route. ',
             'A zero product-entrypoint count does not mean that the native development CLI is absent.', '',
             '| Module | Procedures by implementation kind | Native package owner | Product entrypoints | Product integrated | Independent accepted |',
             '|---|---|---|---:|---|---|']
    for module in data['modules']:
        kinds = '; '.join(f'{kind}: {count}' for kind, count in module['kinds'].items())
        packages = ', '.join('`' + p + '`' for p in module['packages']) or 'responsibility owned by composition'
        lines.append('| ' + ' | '.join([module['id'], kinds, packages,
                     str(module['ordinary_product_entrypoints']),
                     str(module['native_product_integrated']).lower(),
                     str(module['independent_accepted']).lower()]) + ' |')
    lines += ['', '## Explicit current profile bindings', '',
              'Profiles are selected independently; a larger revision is not an automatic upgrade. ',
              'Local transport, research and offline rows do not alter the consensus revision.', '',
              '| Profile | Consensus revision | Contract | Controlled entrypoint |', '|---|---:|---|---|']
    for profile in data['profiles']:
        document, entry = profile['document'], profile['entrypoint']
        revision = str(profile['consensus_revision']) if profile['consensus_revision'] is not None else 'local/research'
        lines.append('| ' + ' | '.join([profile['id'], revision,
                     f'[{Path(document).stem}](../../{document})',
                     f"[{entry['symbol']}](../../{entry['path']})"]) + ' |')
    lines += ['', '## Registered acceptance boundaries', '', '| Boundary | Accepted |', '|---|---|']
    lines += [f'| `{key}` | {str(value).lower()} |' for key, value in data['acceptance'].items()]
    lines += ['', 'The reporter executes no tests and grants no acceptance. Hosted head and prospective merge ',
              'outcomes must be read from their actual runs. The detailed responsibility map and immutable ',
              'receipts remain authoritative for narrower observations.', '', '## Inputs', '']
    lines += [f'- [{path}](../../{path})' for path in data['authorities']]
    return '\n'.join(line.rstrip() for line in lines) + '\n'


def validate(root: Path = ROOT) -> None:
    if (root / DESTINATION).read_text() != markdown(projection(root)):
        raise ValueError('current implementation/profile summary is stale; regenerate from registries')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    parser.add_argument('--format', choices=['markdown', 'json'], default='markdown')
    args = parser.parse_args()
    data = projection()
    if args.write:
        (ROOT / DESTINATION).write_text(markdown(data))
    elif args.check:
        validate()
        print('current implementation/profile summary matches the existing registries')
    else:
        print(json.dumps(data, sort_keys=True, indent=2) if args.format == 'json' else markdown(data), end='\n')


if __name__ == '__main__':
    main()
