// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chain/workload/challenge.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Challenge struct {
	Id             uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId         uint64 `protobuf:"varint,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Challenger     string `protobuf:"bytes,3,opt,name=challenger,proto3" json:"challenger,omitempty"`
	Worker         string `protobuf:"bytes,4,opt,name=worker,proto3" json:"worker,omitempty"`
	Status         uint64 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Deposit        uint64 `protobuf:"varint,6,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Reason         string `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	EvidenceUri    string `protobuf:"bytes,8,opt,name=evidenceUri,proto3" json:"evidenceUri,omitempty"`
	CreatedHeight  uint64 `protobuf:"varint,9,opt,name=createdHeight,proto3" json:"createdHeight,omitempty"`
	ResolvedHeight uint64 `protobuf:"varint,10,opt,name=resolvedHeight,proto3" json:"resolvedHeight,omitempty"`
}

func (m *Challenge) Reset()         { *m = Challenge{} }
func (m *Challenge) String() string { return proto.CompactTextString(m) }
func (*Challenge) ProtoMessage()    {}
func (*Challenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_8070596fcef8ee31, []int{0}
}
func (m *Challenge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Challenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Challenge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Challenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Challenge.Merge(m, src)
}
func (m *Challenge) XXX_Size() int {
	return m.Size()
}
func (m *Challenge) XXX_DiscardUnknown() {
	xxx_messageInfo_Challenge.DiscardUnknown(m)
}

var xxx_messageInfo_Challenge proto.InternalMessageInfo

func (m *Challenge) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Challenge) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Challenge) GetChallenger() string {
	if m != nil {
		return m.Challenger
	}
	return ""
}

func (m *Challenge) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *Challenge) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Challenge) GetDeposit() uint64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *Challenge) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Challenge) GetEvidenceUri() string {
	if m != nil {
		return m.EvidenceUri
	}
	return ""
}

func (m *Challenge) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *Challenge) GetResolvedHeight() uint64 {
	if m != nil {
		return m.ResolvedHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Challenge)(nil), "chain.workload.Challenge")
}

func init() { proto.RegisterFile("chain/workload/challenge.proto", fileDescriptor_8070596fcef8ee31) }

var fileDescriptor_8070596fcef8ee31 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0xeb, 0x50, 0x52, 0xf2, 0x10, 0x19, 0x3c, 0x54, 0x6f, 0xb2, 0x22, 0x84, 0x50, 0xa7,
	0x16, 0x89, 0x3f, 0x80, 0x05, 0xd6, 0x4a, 0x2c, 0x6c, 0x26, 0x7e, 0x6a, 0xac, 0x46, 0x71, 0x64,
	0x9b, 0x02, 0x7f, 0xc1, 0x4f, 0xf0, 0x2f, 0x8c, 0x1d, 0x19, 0x51, 0xf2, 0x23, 0x28, 0x4e, 0x53,
	0x0a, 0xe3, 0x3d, 0xf7, 0xbe, 0xfb, 0xa4, 0x0b, 0x22, 0x2f, 0xa4, 0xae, 0x16, 0x2f, 0xc6, 0xae,
	0x4b, 0x23, 0xd5, 0x22, 0x2f, 0x64, 0x59, 0x52, 0xb5, 0xa2, 0x79, 0x6d, 0x8d, 0x37, 0x3c, 0x0d,
	0xfe, 0x7c, 0xf0, 0xcf, 0x3f, 0x22, 0x48, 0x6e, 0x87, 0x0c, 0x4f, 0x21, 0xd2, 0x0a, 0x59, 0xc6,
	0x66, 0xe3, 0x65, 0xa4, 0x15, 0x9f, 0x42, 0xec, 0xa5, 0x5b, 0xdf, 0x2b, 0x8c, 0x02, 0xdb, 0x29,
	0x2e, 0x00, 0xf6, 0xc5, 0x16, 0x8f, 0x32, 0x36, 0x4b, 0x96, 0x07, 0xa4, 0xbb, 0xeb, 0x3e, 0x90,
	0xc5, 0x71, 0xf0, 0x76, 0xaa, 0xe3, 0xce, 0x4b, 0xff, 0xec, 0xf0, 0xb8, 0xef, 0xeb, 0x15, 0x47,
	0x98, 0x28, 0xaa, 0x8d, 0xd3, 0x1e, 0xe3, 0x60, 0x0c, 0xb2, 0xbb, 0xb0, 0x24, 0x9d, 0xa9, 0x70,
	0xd2, 0x37, 0xf5, 0x8a, 0x67, 0x70, 0x4a, 0x1b, 0xad, 0xa8, 0xca, 0xe9, 0xc1, 0x6a, 0x3c, 0x09,
	0xe6, 0x21, 0xe2, 0x17, 0x70, 0x96, 0x5b, 0x92, 0x9e, 0xd4, 0x1d, 0xe9, 0x55, 0xe1, 0x31, 0x09,
	0xcd, 0x7f, 0x21, 0xbf, 0x84, 0xd4, 0x92, 0x33, 0xe5, 0x66, 0x1f, 0x83, 0x10, 0xfb, 0x47, 0x6f,
	0xae, 0x3e, 0x1b, 0xc1, 0xb6, 0x8d, 0x60, 0xdf, 0x8d, 0x60, 0xef, 0xad, 0x18, 0x6d, 0x5b, 0x31,
	0xfa, 0x6a, 0xc5, 0xe8, 0x71, 0xda, 0x2f, 0xfe, 0xfa, 0xbb, 0xb9, 0x7f, 0xab, 0xc9, 0x3d, 0xc5,
	0x61, 0xf0, 0xeb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xfc, 0x92, 0x68, 0x92, 0x01, 0x00,
	0x00,
}

func (m *Challenge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Challenge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Challenge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResolvedHeight != 0 {
		i = encodeVarintChallenge(dAtA, i, uint64(m.ResolvedHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintChallenge(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x48
	}
	if len(m.EvidenceUri) > 0 {
		i -= len(m.EvidenceUri)
		copy(dAtA[i:], m.EvidenceUri)
		i = encodeVarintChallenge(dAtA, i, uint64(len(m.EvidenceUri)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintChallenge(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Deposit != 0 {
		i = encodeVarintChallenge(dAtA, i, uint64(m.Deposit))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != 0 {
		i = encodeVarintChallenge(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Worker) > 0 {
		i -= len(m.Worker)
		copy(dAtA[i:], m.Worker)
		i = encodeVarintChallenge(dAtA, i, uint64(len(m.Worker)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Challenger) > 0 {
		i -= len(m.Challenger)
		copy(dAtA[i:], m.Challenger)
		i = encodeVarintChallenge(dAtA, i, uint64(len(m.Challenger)))
		i--
		dAtA[i] = 0x1a
	}
	if m.TaskId != 0 {
		i = encodeVarintChallenge(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintChallenge(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintChallenge(dAtA []byte, offset int, v uint64) int {
	offset -= sovChallenge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Challenge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovChallenge(uint64(m.Id))
	}
	if m.TaskId != 0 {
		n += 1 + sovChallenge(uint64(m.TaskId))
	}
	l = len(m.Challenger)
	if l > 0 {
		n += 1 + l + sovChallenge(uint64(l))
	}
	l = len(m.Worker)
	if l > 0 {
		n += 1 + l + sovChallenge(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovChallenge(uint64(m.Status))
	}
	if m.Deposit != 0 {
		n += 1 + sovChallenge(uint64(m.Deposit))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovChallenge(uint64(l))
	}
	l = len(m.EvidenceUri)
	if l > 0 {
		n += 1 + l + sovChallenge(uint64(l))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovChallenge(uint64(m.CreatedHeight))
	}
	if m.ResolvedHeight != 0 {
		n += 1 + sovChallenge(uint64(m.ResolvedHeight))
	}
	return n
}

func sovChallenge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChallenge(x uint64) (n int) {
	return sovChallenge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Challenge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChallenge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Challenge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Challenge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenger", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChallenge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChallenge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Challenger = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChallenge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChallenge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Worker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			m.Deposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChallenge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChallenge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChallenge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChallenge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvidenceUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedHeight", wireType)
			}
			m.ResolvedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolvedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChallenge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChallenge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChallenge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChallenge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChallenge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChallenge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChallenge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChallenge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChallenge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChallenge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChallenge = fmt.Errorf("proto: unexpected end of group")
)
