// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chain/workload/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	WorkloadDenom                 string `protobuf:"bytes,1,opt,name=workload_denom,json=workloadDenom,proto3" json:"workload_denom,omitempty"`
	ChallengeWindowBlocks         uint64 `protobuf:"varint,2,opt,name=challenge_window_blocks,json=challengeWindowBlocks,proto3" json:"challenge_window_blocks,omitempty"`
	ChallengeDeposit              uint64 `protobuf:"varint,3,opt,name=challenge_deposit,json=challengeDeposit,proto3" json:"challenge_deposit,omitempty"`
	ChallengerSlashPercent        uint64 `protobuf:"varint,4,opt,name=challenger_slash_percent,json=challengerSlashPercent,proto3" json:"challenger_slash_percent,omitempty"`
	WorkerSlashPercentOnBadResult uint64 `protobuf:"varint,5,opt,name=worker_slash_percent_on_bad_result,json=workerSlashPercentOnBadResult,proto3" json:"worker_slash_percent_on_bad_result,omitempty"`
	RevealWindowBlocks            uint64 `protobuf:"varint,6,opt,name=reveal_window_blocks,json=revealWindowBlocks,proto3" json:"reveal_window_blocks,omitempty"`
	AllowLegacySubmitResult       bool   `protobuf:"varint,7,opt,name=allow_legacy_submit_result,json=allowLegacySubmitResult,proto3" json:"allow_legacy_submit_result,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cd2d01c1dca144b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWorkloadDenom() string {
	if m != nil {
		return m.WorkloadDenom
	}
	return ""
}

func (m *Params) GetChallengeWindowBlocks() uint64 {
	if m != nil {
		return m.ChallengeWindowBlocks
	}
	return 0
}

func (m *Params) GetChallengeDeposit() uint64 {
	if m != nil {
		return m.ChallengeDeposit
	}
	return 0
}

func (m *Params) GetChallengerSlashPercent() uint64 {
	if m != nil {
		return m.ChallengerSlashPercent
	}
	return 0
}

func (m *Params) GetWorkerSlashPercentOnBadResult() uint64 {
	if m != nil {
		return m.WorkerSlashPercentOnBadResult
	}
	return 0
}

func (m *Params) GetRevealWindowBlocks() uint64 {
	if m != nil {
		return m.RevealWindowBlocks
	}
	return 0
}

func (m *Params) GetAllowLegacySubmitResult() bool {
	if m != nil {
		return m.AllowLegacySubmitResult
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "chain.workload.Params")
}

func init() { proto.RegisterFile("chain/workload/params.proto", fileDescriptor_5cd2d01c1dca144b) }

var fileDescriptor_5cd2d01c1dca144b = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4a, 0xe3, 0x40,
	0x18, 0xc7, 0x3b, 0xdb, 0x6e, 0x77, 0x77, 0x60, 0xcb, 0x76, 0xe8, 0xb6, 0xa1, 0x62, 0x0c, 0x05,
	0xa1, 0x28, 0x34, 0x05, 0x41, 0x44, 0x6f, 0xa5, 0x17, 0x41, 0xb0, 0xa4, 0x07, 0xc1, 0xcb, 0x30,
	0x49, 0x86, 0x34, 0x74, 0x32, 0x13, 0x32, 0xa9, 0xb1, 0xaf, 0xe0, 0xc9, 0x47, 0xf0, 0xec, 0xc9,
	0xc7, 0xf0, 0xd8, 0xa3, 0x47, 0x69, 0x0f, 0xfa, 0x18, 0x92, 0x19, 0xd2, 0x6a, 0xbd, 0x84, 0xe1,
	0xff, 0xfb, 0xff, 0x66, 0xf2, 0xf1, 0xc1, 0x1d, 0x6f, 0x42, 0x42, 0x6e, 0x67, 0x22, 0x99, 0x32,
	0x41, 0x7c, 0x3b, 0x26, 0x09, 0x89, 0x64, 0x2f, 0x4e, 0x44, 0x2a, 0x50, 0x4d, 0xc1, 0x5e, 0x01,
	0xdb, 0x75, 0x12, 0x85, 0x5c, 0xd8, 0xea, 0xab, 0x2b, 0xed, 0x46, 0x20, 0x02, 0xa1, 0x8e, 0x76,
	0x7e, 0xd2, 0x69, 0xe7, 0xb1, 0x0c, 0xab, 0x23, 0x75, 0x13, 0xda, 0x87, 0xb5, 0xc2, 0xc7, 0x3e,
	0xe5, 0x22, 0x32, 0x80, 0x05, 0xba, 0x7f, 0x9c, 0xbf, 0x45, 0x3a, 0xcc, 0x43, 0x74, 0x0c, 0x5b,
	0xde, 0x84, 0x30, 0x46, 0x79, 0x40, 0x71, 0x16, 0x72, 0x5f, 0x64, 0xd8, 0x65, 0xc2, 0x9b, 0x4a,
	0xe3, 0x87, 0x05, 0xba, 0x15, 0xe7, 0xff, 0x1a, 0x5f, 0x29, 0x3a, 0x50, 0x10, 0x1d, 0xc2, 0xfa,
	0xc6, 0xf3, 0x69, 0x2c, 0x64, 0x98, 0x1a, 0x65, 0x65, 0xfc, 0x5b, 0x83, 0xa1, 0xce, 0xd1, 0x09,
	0x34, 0xd6, 0x59, 0x82, 0x25, 0x23, 0x72, 0x82, 0x63, 0x9a, 0x78, 0x94, 0xa7, 0x46, 0x45, 0x39,
	0xcd, 0x0d, 0x1f, 0xe7, 0x78, 0xa4, 0x29, 0x3a, 0x87, 0x9d, 0xfc, 0x7f, 0xb7, 0x2d, 0x2c, 0x38,
	0x76, 0x89, 0x8f, 0x13, 0x2a, 0x67, 0x2c, 0x35, 0x7e, 0xaa, 0x3b, 0x76, 0x75, 0xf3, 0xb3, 0x7f,
	0xc9, 0x07, 0xc4, 0x77, 0x54, 0x09, 0xf5, 0x61, 0x23, 0xa1, 0x37, 0x94, 0xb0, 0xad, 0x31, 0xab,
	0x4a, 0x46, 0x9a, 0x7d, 0x99, 0xf1, 0x0c, 0xb6, 0x09, 0x63, 0x22, 0xc3, 0x8c, 0x06, 0xc4, 0x9b,
	0x63, 0x39, 0x73, 0xa3, 0x30, 0x2d, 0x1e, 0xfd, 0x65, 0x81, 0xee, 0x6f, 0xa7, 0xa5, 0x1a, 0x17,
	0xaa, 0x30, 0x56, 0x5c, 0x3f, 0x77, 0x6a, 0xbd, 0x3f, 0xec, 0x81, 0xbb, 0xb7, 0xa7, 0x83, 0x96,
	0xde, 0xf4, 0xed, 0x66, 0xd7, 0x7a, 0x43, 0x83, 0xfe, 0xf3, 0xd2, 0x04, 0x8b, 0xa5, 0x09, 0x5e,
	0x97, 0x26, 0xb8, 0x5f, 0x99, 0xa5, 0xc5, 0xca, 0x2c, 0xbd, 0xac, 0xcc, 0xd2, 0x75, 0xf3, 0x9b,
	0x92, 0xce, 0x63, 0x2a, 0xdd, 0xaa, 0xda, 0xf2, 0xd1, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab,
	0xee, 0xc5, 0x1a, 0x3d, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.WorkloadDenom != that1.WorkloadDenom {
		return false
	}
	if this.ChallengeWindowBlocks != that1.ChallengeWindowBlocks {
		return false
	}
	if this.ChallengeDeposit != that1.ChallengeDeposit {
		return false
	}
	if this.ChallengerSlashPercent != that1.ChallengerSlashPercent {
		return false
	}
	if this.WorkerSlashPercentOnBadResult != that1.WorkerSlashPercentOnBadResult {
		return false
	}
	if this.RevealWindowBlocks != that1.RevealWindowBlocks {
		return false
	}
	if this.AllowLegacySubmitResult != that1.AllowLegacySubmitResult {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AllowLegacySubmitResult {
		i--
		if m.AllowLegacySubmitResult {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.RevealWindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RevealWindowBlocks))
		i--
		dAtA[i] = 0x30
	}
	if m.WorkerSlashPercentOnBadResult != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WorkerSlashPercentOnBadResult))
		i--
		dAtA[i] = 0x28
	}
	if m.ChallengerSlashPercent != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ChallengerSlashPercent))
		i--
		dAtA[i] = 0x20
	}
	if m.ChallengeDeposit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ChallengeDeposit))
		i--
		dAtA[i] = 0x18
	}
	if m.ChallengeWindowBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ChallengeWindowBlocks))
		i--
		dAtA[i] = 0x10
	}
	if len(m.WorkloadDenom) > 0 {
		i -= len(m.WorkloadDenom)
		copy(dAtA[i:], m.WorkloadDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.WorkloadDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.WorkloadDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.ChallengeWindowBlocks != 0 {
		n += 1 + sovParams(uint64(m.ChallengeWindowBlocks))
	}
	if m.ChallengeDeposit != 0 {
		n += 1 + sovParams(uint64(m.ChallengeDeposit))
	}
	if m.ChallengerSlashPercent != 0 {
		n += 1 + sovParams(uint64(m.ChallengerSlashPercent))
	}
	if m.WorkerSlashPercentOnBadResult != 0 {
		n += 1 + sovParams(uint64(m.WorkerSlashPercentOnBadResult))
	}
	if m.RevealWindowBlocks != 0 {
		n += 1 + sovParams(uint64(m.RevealWindowBlocks))
	}
	if m.AllowLegacySubmitResult {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkloadDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WorkloadDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeWindowBlocks", wireType)
			}
			m.ChallengeWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeDeposit", wireType)
			}
			m.ChallengeDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeDeposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengerSlashPercent", wireType)
			}
			m.ChallengerSlashPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengerSlashPercent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerSlashPercentOnBadResult", wireType)
			}
			m.WorkerSlashPercentOnBadResult = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkerSlashPercentOnBadResult |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealWindowBlocks", wireType)
			}
			m.RevealWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevealWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowLegacySubmitResult", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowLegacySubmitResult = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
