// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chain/workload/task.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IpfsHash string `protobuf:"bytes,2,opt,name=ipfsHash,proto3" json:"ipfsHash,omitempty"`
	Bounty   uint64 `protobuf:"varint,3,opt,name=bounty,proto3" json:"bounty,omitempty"`
	// Task status (canonical semantics):
	// 0 OPEN
	// 1 ASSIGNED
	// 2 COMMITTED
	// 3 REVEALED (legacy alias: RESULT_SUBMITTED)
	// 4 CHALLENGED
	// 5 COMPLETED
	// 6 SLASHED
	Status                  uint64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Worker                  string `protobuf:"bytes,5,opt,name=worker,proto3" json:"worker,omitempty"`
	ResultHash              string `protobuf:"bytes,6,opt,name=resultHash,proto3" json:"resultHash,omitempty"`
	Creator                 string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	ChallengeDeadlineHeight uint64 `protobuf:"varint,8,opt,name=challengeDeadlineHeight,proto3" json:"challengeDeadlineHeight,omitempty"`
	Challenger              string `protobuf:"bytes,9,opt,name=challenger,proto3" json:"challenger,omitempty"`
	ChallengeId             uint64 `protobuf:"varint,10,opt,name=challengeId,proto3" json:"challengeId,omitempty"`
	CommitHash              string `protobuf:"bytes,11,opt,name=commitHash,proto3" json:"commitHash,omitempty"`
	CommitHeight            uint64 `protobuf:"varint,12,opt,name=commitHeight,proto3" json:"commitHeight,omitempty"`
	RevealDeadlineHeight    uint64 `protobuf:"varint,13,opt,name=revealDeadlineHeight,proto3" json:"revealDeadlineHeight,omitempty"`
	ResultUri               string `protobuf:"bytes,14,opt,name=resultUri,proto3" json:"resultUri,omitempty"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea63c3dad7959bdd, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Task.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return m.Size()
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetIpfsHash() string {
	if m != nil {
		return m.IpfsHash
	}
	return ""
}

func (m *Task) GetBounty() uint64 {
	if m != nil {
		return m.Bounty
	}
	return 0
}

func (m *Task) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Task) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *Task) GetResultHash() string {
	if m != nil {
		return m.ResultHash
	}
	return ""
}

func (m *Task) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Task) GetChallengeDeadlineHeight() uint64 {
	if m != nil {
		return m.ChallengeDeadlineHeight
	}
	return 0
}

func (m *Task) GetChallenger() string {
	if m != nil {
		return m.Challenger
	}
	return ""
}

func (m *Task) GetChallengeId() uint64 {
	if m != nil {
		return m.ChallengeId
	}
	return 0
}

func (m *Task) GetCommitHash() string {
	if m != nil {
		return m.CommitHash
	}
	return ""
}

func (m *Task) GetCommitHeight() uint64 {
	if m != nil {
		return m.CommitHeight
	}
	return 0
}

func (m *Task) GetRevealDeadlineHeight() uint64 {
	if m != nil {
		return m.RevealDeadlineHeight
	}
	return 0
}

func (m *Task) GetResultUri() string {
	if m != nil {
		return m.ResultUri
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "chain.workload.Task")
}

func init() { proto.RegisterFile("chain/workload/task.proto", fileDescriptor_ea63c3dad7959bdd) }

var fileDescriptor_ea63c3dad7959bdd = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x3f, 0x4f, 0x72, 0x31,
	0x18, 0xc5, 0x29, 0xf0, 0xf2, 0xe7, 0x81, 0x97, 0xa1, 0x31, 0x58, 0x8d, 0x69, 0x08, 0x13, 0x13,
	0x18, 0x5d, 0x9c, 0x8d, 0x03, 0xae, 0x44, 0x17, 0xb7, 0xc2, 0xad, 0xdc, 0x86, 0x72, 0x4b, 0xda,
	0xa2, 0xf2, 0x2d, 0xfc, 0x54, 0xc6, 0x91, 0xd1, 0xd1, 0xc0, 0x17, 0x31, 0xf7, 0xe9, 0xe5, 0x82,
	0x46, 0xc7, 0xf3, 0x3b, 0xcd, 0x39, 0x4f, 0x9a, 0x03, 0x27, 0x93, 0x58, 0xa8, 0x64, 0xf0, 0x6c,
	0xec, 0x4c, 0x1b, 0x11, 0x0d, 0xbc, 0x70, 0xb3, 0xfe, 0xc2, 0x1a, 0x6f, 0x68, 0x0b, 0xad, 0xfe,
	0xce, 0xea, 0xbe, 0x95, 0xa0, 0x7c, 0x27, 0xdc, 0x8c, 0xb6, 0xa0, 0xa8, 0x22, 0x46, 0x3a, 0xa4,
	0x57, 0x1e, 0x15, 0x55, 0x44, 0x4f, 0xa1, 0xa6, 0x16, 0x8f, 0x6e, 0x28, 0x5c, 0xcc, 0x8a, 0x1d,
	0xd2, 0xab, 0x8f, 0x72, 0x4d, 0xdb, 0x50, 0x19, 0x9b, 0x65, 0xe2, 0x57, 0xac, 0x84, 0xef, 0x33,
	0x95, 0x72, 0xe7, 0x85, 0x5f, 0x3a, 0x56, 0x0e, 0x3c, 0xa8, 0x94, 0xa7, 0x85, 0xd2, 0xb2, 0x7f,
	0x98, 0x94, 0x29, 0xca, 0x01, 0xac, 0x74, 0x4b, 0xed, 0xb1, 0xa5, 0x82, 0xde, 0x01, 0xa1, 0x0c,
	0xaa, 0x13, 0x2b, 0x85, 0x37, 0x96, 0x55, 0xd1, 0xdc, 0x49, 0x7a, 0x05, 0xc7, 0x93, 0x58, 0x68,
	0x2d, 0x93, 0xa9, 0xbc, 0x91, 0x22, 0xd2, 0x2a, 0x91, 0x43, 0xa9, 0xa6, 0xb1, 0x67, 0x35, 0xac,
	0xfe, 0xcb, 0x4e, 0x3b, 0x73, 0xcb, 0xb2, 0x7a, 0xe8, 0xdc, 0x13, 0xda, 0x81, 0x46, 0xae, 0x6e,
	0x23, 0x06, 0x98, 0x76, 0x88, 0x30, 0xc1, 0xcc, 0xe7, 0x2a, 0x5c, 0xdd, 0xc8, 0x12, 0x72, 0x42,
	0xbb, 0xd0, 0xcc, 0x54, 0x38, 0xa8, 0x89, 0x11, 0xdf, 0x18, 0xbd, 0x80, 0x23, 0x2b, 0x9f, 0xa4,
	0xd0, 0x3f, 0x8e, 0xff, 0x8f, 0x6f, 0x7f, 0xf5, 0xe8, 0x19, 0xd4, 0xc3, 0xdf, 0xdc, 0x5b, 0xc5,
	0x5a, 0x58, 0xbb, 0x07, 0xd7, 0xe7, 0xef, 0x1b, 0x4e, 0xd6, 0x1b, 0x4e, 0x3e, 0x37, 0x9c, 0xbc,
	0x6e, 0x79, 0x61, 0xbd, 0xe5, 0x85, 0x8f, 0x2d, 0x2f, 0x3c, 0xb4, 0xc3, 0x1a, 0x5e, 0x0e, 0xf6,
	0xb0, 0x5a, 0x48, 0x37, 0xae, 0xe0, 0x22, 0x2e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x9c,
	0x8d, 0x75, 0x2e, 0x02, 0x00, 0x00,
}

func (m *Task) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Task) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Task) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResultUri) > 0 {
		i -= len(m.ResultUri)
		copy(dAtA[i:], m.ResultUri)
		i = encodeVarintTask(dAtA, i, uint64(len(m.ResultUri)))
		i--
		dAtA[i] = 0x72
	}
	if m.RevealDeadlineHeight != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.RevealDeadlineHeight))
		i--
		dAtA[i] = 0x68
	}
	if m.CommitHeight != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.CommitHeight))
		i--
		dAtA[i] = 0x60
	}
	if len(m.CommitHash) > 0 {
		i -= len(m.CommitHash)
		copy(dAtA[i:], m.CommitHash)
		i = encodeVarintTask(dAtA, i, uint64(len(m.CommitHash)))
		i--
		dAtA[i] = 0x5a
	}
	if m.ChallengeId != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.ChallengeId))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Challenger) > 0 {
		i -= len(m.Challenger)
		copy(dAtA[i:], m.Challenger)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Challenger)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ChallengeDeadlineHeight != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.ChallengeDeadlineHeight))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ResultHash) > 0 {
		i -= len(m.ResultHash)
		copy(dAtA[i:], m.ResultHash)
		i = encodeVarintTask(dAtA, i, uint64(len(m.ResultHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Worker) > 0 {
		i -= len(m.Worker)
		copy(dAtA[i:], m.Worker)
		i = encodeVarintTask(dAtA, i, uint64(len(m.Worker)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.Bounty != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Bounty))
		i--
		dAtA[i] = 0x18
	}
	if len(m.IpfsHash) > 0 {
		i -= len(m.IpfsHash)
		copy(dAtA[i:], m.IpfsHash)
		i = encodeVarintTask(dAtA, i, uint64(len(m.IpfsHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTask(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTask(dAtA []byte, offset int, v uint64) int {
	offset -= sovTask(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Task) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTask(uint64(m.Id))
	}
	l = len(m.IpfsHash)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.Bounty != 0 {
		n += 1 + sovTask(uint64(m.Bounty))
	}
	if m.Status != 0 {
		n += 1 + sovTask(uint64(m.Status))
	}
	l = len(m.Worker)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.ResultHash)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.ChallengeDeadlineHeight != 0 {
		n += 1 + sovTask(uint64(m.ChallengeDeadlineHeight))
	}
	l = len(m.Challenger)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.ChallengeId != 0 {
		n += 1 + sovTask(uint64(m.ChallengeId))
	}
	l = len(m.CommitHash)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	if m.CommitHeight != 0 {
		n += 1 + sovTask(uint64(m.CommitHeight))
	}
	if m.RevealDeadlineHeight != 0 {
		n += 1 + sovTask(uint64(m.RevealDeadlineHeight))
	}
	l = len(m.ResultUri)
	if l > 0 {
		n += 1 + l + sovTask(uint64(l))
	}
	return n
}

func sovTask(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTask(x uint64) (n int) {
	return sovTask(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Task) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTask
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Task: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Task: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IpfsHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IpfsHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bounty", wireType)
			}
			m.Bounty = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Bounty |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Worker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeDeadlineHeight", wireType)
			}
			m.ChallengeDeadlineHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeDeadlineHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenger", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Challenger = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeId", wireType)
			}
			m.ChallengeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChallengeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitHeight", wireType)
			}
			m.CommitHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealDeadlineHeight", wireType)
			}
			m.RevealDeadlineHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevealDeadlineHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTask
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTask
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTask
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResultUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTask(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTask
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTask(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTask
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTask
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTask
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTask
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTask
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTask        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTask          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTask = fmt.Errorf("proto: unexpected end of group")
)
