// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: chain/workload/tx.proto

package workload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName      = "/chain.workload.Msg/UpdateParams"
	Msg_CreateTask_FullMethodName        = "/chain.workload.Msg/CreateTask"
	Msg_AcceptTask_FullMethodName        = "/chain.workload.Msg/AcceptTask"
	Msg_UpdateTask_FullMethodName        = "/chain.workload.Msg/UpdateTask"
	Msg_DeleteTask_FullMethodName        = "/chain.workload.Msg/DeleteTask"
	Msg_RegisterWorker_FullMethodName    = "/chain.workload.Msg/RegisterWorker"
	Msg_SlashWorker_FullMethodName       = "/chain.workload.Msg/SlashWorker"
	Msg_UnregisterWorker_FullMethodName  = "/chain.workload.Msg/UnregisterWorker"
	Msg_RequestUnbonding_FullMethodName  = "/chain.workload.Msg/RequestUnbonding"
	Msg_FinalizeUnbonding_FullMethodName = "/chain.workload.Msg/FinalizeUnbonding"
	Msg_ExtendUnbonding_FullMethodName   = "/chain.workload.Msg/ExtendUnbonding"
	Msg_CommitResult_FullMethodName      = "/chain.workload.Msg/CommitResult"
	Msg_RevealResult_FullMethodName      = "/chain.workload.Msg/RevealResult"
	Msg_SubmitResult_FullMethodName      = "/chain.workload.Msg/SubmitResult"
	Msg_ChallengeResult_FullMethodName   = "/chain.workload.Msg/ChallengeResult"
	Msg_ResolveChallenge_FullMethodName  = "/chain.workload.Msg/ResolveChallenge"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateTask(ctx context.Context, in *MsgCreateTask, opts ...grpc.CallOption) (*MsgCreateTaskResponse, error)
	AcceptTask(ctx context.Context, in *MsgAcceptTask, opts ...grpc.CallOption) (*MsgAcceptTaskResponse, error)
	UpdateTask(ctx context.Context, in *MsgUpdateTask, opts ...grpc.CallOption) (*MsgUpdateTaskResponse, error)
	DeleteTask(ctx context.Context, in *MsgDeleteTask, opts ...grpc.CallOption) (*MsgDeleteTaskResponse, error)
	RegisterWorker(ctx context.Context, in *MsgRegisterWorker, opts ...grpc.CallOption) (*MsgRegisterWorkerResponse, error)
	SlashWorker(ctx context.Context, in *MsgSlashWorker, opts ...grpc.CallOption) (*MsgSlashWorkerResponse, error)
	UnregisterWorker(ctx context.Context, in *MsgUnregisterWorker, opts ...grpc.CallOption) (*MsgUnregisterWorkerResponse, error)
	RequestUnbonding(ctx context.Context, in *MsgRequestUnbonding, opts ...grpc.CallOption) (*MsgRequestUnbondingResponse, error)
	FinalizeUnbonding(ctx context.Context, in *MsgFinalizeUnbonding, opts ...grpc.CallOption) (*MsgFinalizeUnbondingResponse, error)
	ExtendUnbonding(ctx context.Context, in *MsgExtendUnbonding, opts ...grpc.CallOption) (*MsgExtendUnbondingResponse, error)
	CommitResult(ctx context.Context, in *MsgCommitResult, opts ...grpc.CallOption) (*MsgCommitResultResponse, error)
	RevealResult(ctx context.Context, in *MsgRevealResult, opts ...grpc.CallOption) (*MsgRevealResultResponse, error)
	SubmitResult(ctx context.Context, in *MsgSubmitResult, opts ...grpc.CallOption) (*MsgSubmitResultResponse, error)
	ChallengeResult(ctx context.Context, in *MsgChallengeResult, opts ...grpc.CallOption) (*MsgChallengeResultResponse, error)
	ResolveChallenge(ctx context.Context, in *MsgResolveChallenge, opts ...grpc.CallOption) (*MsgResolveChallengeResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateTask(ctx context.Context, in *MsgCreateTask, opts ...grpc.CallOption) (*MsgCreateTaskResponse, error) {
	out := new(MsgCreateTaskResponse)
	err := c.cc.Invoke(ctx, Msg_CreateTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AcceptTask(ctx context.Context, in *MsgAcceptTask, opts ...grpc.CallOption) (*MsgAcceptTaskResponse, error) {
	out := new(MsgAcceptTaskResponse)
	err := c.cc.Invoke(ctx, Msg_AcceptTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateTask(ctx context.Context, in *MsgUpdateTask, opts ...grpc.CallOption) (*MsgUpdateTaskResponse, error) {
	out := new(MsgUpdateTaskResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteTask(ctx context.Context, in *MsgDeleteTask, opts ...grpc.CallOption) (*MsgDeleteTaskResponse, error) {
	out := new(MsgDeleteTaskResponse)
	err := c.cc.Invoke(ctx, Msg_DeleteTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterWorker(ctx context.Context, in *MsgRegisterWorker, opts ...grpc.CallOption) (*MsgRegisterWorkerResponse, error) {
	out := new(MsgRegisterWorkerResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SlashWorker(ctx context.Context, in *MsgSlashWorker, opts ...grpc.CallOption) (*MsgSlashWorkerResponse, error) {
	out := new(MsgSlashWorkerResponse)
	err := c.cc.Invoke(ctx, Msg_SlashWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterWorker(ctx context.Context, in *MsgUnregisterWorker, opts ...grpc.CallOption) (*MsgUnregisterWorkerResponse, error) {
	out := new(MsgUnregisterWorkerResponse)
	err := c.cc.Invoke(ctx, Msg_UnregisterWorker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestUnbonding(ctx context.Context, in *MsgRequestUnbonding, opts ...grpc.CallOption) (*MsgRequestUnbondingResponse, error) {
	out := new(MsgRequestUnbondingResponse)
	err := c.cc.Invoke(ctx, Msg_RequestUnbonding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FinalizeUnbonding(ctx context.Context, in *MsgFinalizeUnbonding, opts ...grpc.CallOption) (*MsgFinalizeUnbondingResponse, error) {
	out := new(MsgFinalizeUnbondingResponse)
	err := c.cc.Invoke(ctx, Msg_FinalizeUnbonding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExtendUnbonding(ctx context.Context, in *MsgExtendUnbonding, opts ...grpc.CallOption) (*MsgExtendUnbondingResponse, error) {
	out := new(MsgExtendUnbondingResponse)
	err := c.cc.Invoke(ctx, Msg_ExtendUnbonding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CommitResult(ctx context.Context, in *MsgCommitResult, opts ...grpc.CallOption) (*MsgCommitResultResponse, error) {
	out := new(MsgCommitResultResponse)
	err := c.cc.Invoke(ctx, Msg_CommitResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevealResult(ctx context.Context, in *MsgRevealResult, opts ...grpc.CallOption) (*MsgRevealResultResponse, error) {
	out := new(MsgRevealResultResponse)
	err := c.cc.Invoke(ctx, Msg_RevealResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitResult(ctx context.Context, in *MsgSubmitResult, opts ...grpc.CallOption) (*MsgSubmitResultResponse, error) {
	out := new(MsgSubmitResultResponse)
	err := c.cc.Invoke(ctx, Msg_SubmitResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChallengeResult(ctx context.Context, in *MsgChallengeResult, opts ...grpc.CallOption) (*MsgChallengeResultResponse, error) {
	out := new(MsgChallengeResultResponse)
	err := c.cc.Invoke(ctx, Msg_ChallengeResult_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ResolveChallenge(ctx context.Context, in *MsgResolveChallenge, opts ...grpc.CallOption) (*MsgResolveChallengeResponse, error) {
	out := new(MsgResolveChallengeResponse)
	err := c.cc.Invoke(ctx, Msg_ResolveChallenge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateTask(context.Context, *MsgCreateTask) (*MsgCreateTaskResponse, error)
	AcceptTask(context.Context, *MsgAcceptTask) (*MsgAcceptTaskResponse, error)
	UpdateTask(context.Context, *MsgUpdateTask) (*MsgUpdateTaskResponse, error)
	DeleteTask(context.Context, *MsgDeleteTask) (*MsgDeleteTaskResponse, error)
	RegisterWorker(context.Context, *MsgRegisterWorker) (*MsgRegisterWorkerResponse, error)
	SlashWorker(context.Context, *MsgSlashWorker) (*MsgSlashWorkerResponse, error)
	UnregisterWorker(context.Context, *MsgUnregisterWorker) (*MsgUnregisterWorkerResponse, error)
	RequestUnbonding(context.Context, *MsgRequestUnbonding) (*MsgRequestUnbondingResponse, error)
	FinalizeUnbonding(context.Context, *MsgFinalizeUnbonding) (*MsgFinalizeUnbondingResponse, error)
	ExtendUnbonding(context.Context, *MsgExtendUnbonding) (*MsgExtendUnbondingResponse, error)
	CommitResult(context.Context, *MsgCommitResult) (*MsgCommitResultResponse, error)
	RevealResult(context.Context, *MsgRevealResult) (*MsgRevealResultResponse, error)
	SubmitResult(context.Context, *MsgSubmitResult) (*MsgSubmitResultResponse, error)
	ChallengeResult(context.Context, *MsgChallengeResult) (*MsgChallengeResultResponse, error)
	ResolveChallenge(context.Context, *MsgResolveChallenge) (*MsgResolveChallengeResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateTask(context.Context, *MsgCreateTask) (*MsgCreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedMsgServer) AcceptTask(context.Context, *MsgAcceptTask) (*MsgAcceptTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptTask not implemented")
}
func (UnimplementedMsgServer) UpdateTask(context.Context, *MsgUpdateTask) (*MsgUpdateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedMsgServer) DeleteTask(context.Context, *MsgDeleteTask) (*MsgDeleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedMsgServer) RegisterWorker(context.Context, *MsgRegisterWorker) (*MsgRegisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedMsgServer) SlashWorker(context.Context, *MsgSlashWorker) (*MsgSlashWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SlashWorker not implemented")
}
func (UnimplementedMsgServer) UnregisterWorker(context.Context, *MsgUnregisterWorker) (*MsgUnregisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterWorker not implemented")
}
func (UnimplementedMsgServer) RequestUnbonding(context.Context, *MsgRequestUnbonding) (*MsgRequestUnbondingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUnbonding not implemented")
}
func (UnimplementedMsgServer) FinalizeUnbonding(context.Context, *MsgFinalizeUnbonding) (*MsgFinalizeUnbondingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeUnbonding not implemented")
}
func (UnimplementedMsgServer) ExtendUnbonding(context.Context, *MsgExtendUnbonding) (*MsgExtendUnbondingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendUnbonding not implemented")
}
func (UnimplementedMsgServer) CommitResult(context.Context, *MsgCommitResult) (*MsgCommitResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitResult not implemented")
}
func (UnimplementedMsgServer) RevealResult(context.Context, *MsgRevealResult) (*MsgRevealResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevealResult not implemented")
}
func (UnimplementedMsgServer) SubmitResult(context.Context, *MsgSubmitResult) (*MsgSubmitResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedMsgServer) ChallengeResult(context.Context, *MsgChallengeResult) (*MsgChallengeResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChallengeResult not implemented")
}
func (UnimplementedMsgServer) ResolveChallenge(context.Context, *MsgResolveChallenge) (*MsgResolveChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveChallenge not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTask(ctx, req.(*MsgCreateTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AcceptTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAcceptTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AcceptTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AcceptTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AcceptTask(ctx, req.(*MsgAcceptTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateTask(ctx, req.(*MsgUpdateTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteTask(ctx, req.(*MsgDeleteTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterWorker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterWorker(ctx, req.(*MsgRegisterWorker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SlashWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSlashWorker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SlashWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SlashWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SlashWorker(ctx, req.(*MsgSlashWorker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterWorker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UnregisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterWorker(ctx, req.(*MsgUnregisterWorker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestUnbonding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestUnbonding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestUnbonding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RequestUnbonding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestUnbonding(ctx, req.(*MsgRequestUnbonding))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FinalizeUnbonding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinalizeUnbonding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinalizeUnbonding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FinalizeUnbonding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinalizeUnbonding(ctx, req.(*MsgFinalizeUnbonding))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExtendUnbonding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExtendUnbonding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExtendUnbonding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ExtendUnbonding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExtendUnbonding(ctx, req.(*MsgExtendUnbonding))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CommitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCommitResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CommitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CommitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CommitResult(ctx, req.(*MsgCommitResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevealResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevealResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevealResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevealResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevealResult(ctx, req.(*MsgRevealResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitResult(ctx, req.(*MsgSubmitResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChallengeResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChallengeResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChallengeResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ChallengeResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChallengeResult(ctx, req.(*MsgChallengeResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ResolveChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgResolveChallenge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ResolveChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ResolveChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ResolveChallenge(ctx, req.(*MsgResolveChallenge))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chain.workload.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _Msg_CreateTask_Handler,
		},
		{
			MethodName: "AcceptTask",
			Handler:    _Msg_AcceptTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _Msg_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _Msg_DeleteTask_Handler,
		},
		{
			MethodName: "RegisterWorker",
			Handler:    _Msg_RegisterWorker_Handler,
		},
		{
			MethodName: "SlashWorker",
			Handler:    _Msg_SlashWorker_Handler,
		},
		{
			MethodName: "UnregisterWorker",
			Handler:    _Msg_UnregisterWorker_Handler,
		},
		{
			MethodName: "RequestUnbonding",
			Handler:    _Msg_RequestUnbonding_Handler,
		},
		{
			MethodName: "FinalizeUnbonding",
			Handler:    _Msg_FinalizeUnbonding_Handler,
		},
		{
			MethodName: "ExtendUnbonding",
			Handler:    _Msg_ExtendUnbonding_Handler,
		},
		{
			MethodName: "CommitResult",
			Handler:    _Msg_CommitResult_Handler,
		},
		{
			MethodName: "RevealResult",
			Handler:    _Msg_RevealResult_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _Msg_SubmitResult_Handler,
		},
		{
			MethodName: "ChallengeResult",
			Handler:    _Msg_ChallengeResult_Handler,
		},
		{
			MethodName: "ResolveChallenge",
			Handler:    _Msg_ResolveChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chain/workload/tx.proto",
}
