version: 1
accounts:
- name: alice
  coins:
  - 200000utrnm
  - 200000000stake
- name: bob
  coins:
  - 10000utrnm
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5utrnm
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
build:
  main: ./cmd/chaind
